/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutCenter: typeof import('./src/components/AboutCenter.vue')['default']
    Contagem: typeof import('./src/components/contagem.vue')['default']
    ContatoFooter: typeof import('./src/components/ContatoFooter.vue')['default']
    Depoimentos: typeof import('./src/components/depoimentos.vue')['default']
    Encontrar: typeof import('./src/components/encontrar.vue')['default']
    Entre: typeof import('./src/components/entre.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Loca: typeof import('./src/components/loca.vue')['default']
    Preloader: typeof import('./src/components/preloader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sections: typeof import('./src/components/sections.vue')['default']
    WhatsAppButton: typeof import('./src/components/WhatsAppButton.vue')['default']
  }
}
